server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/product/**
        - id: orderManagement
          uri: 'http://localhost:8091'
          predicates:
            - Path=/api/order/**
eureka:
  client:
    register-with-eureka: false
